### ISSUE TITLE
2021/04 strategic highlight日本語翻訳ドラフトへのコメント用

### ISSUE THREAD

**Issue by himorin** [himorin/w3c-memo#11]
レビュー用github.ioページ: https://himorin.github.io/w3c-memo/translations/2021-04-highlights.html
チェック項目

- [x] リンク
- [x] ページ内のメニューのリンクチェック
- [x] WG/BG/CG/IGを～グループ表記に

/cc @yonaomi

**Comment by xfq** [comment]
[将来に向けた標準化領域の探索](https://himorin.github.io/w3c-memo/translations/2021-04-highlights.html#pipeline)には翻訳されていない文があるようです。


> The Strategy incubation pipeline documents the exploration of potential new work in phases of

I sent a PR to fix some other minor issues: https://github.com/himorin/w3c-memo/pull/12

**Comment by himorin** [comment]
> [将来に向けた標準化領域の探索](https://himorin.github.io/w3c-memo/translations/2021-04-highlights.html#pipeline)には翻訳されていない文があるようです。
> 
> > The Strategy incubation pipeline documents the exploration of potential new work in phases of
> 
> I sent a PR to fix some other minor issues: #12

Thank you for pointing these. It seems I've failed something during c&p from last one.
Also merged #12.

**Comment by himorin** [comment]
link checked (found one broken fragment), and menu link checked.

**Comment by himorin** [comment]
fixed *G to ～グループ

**Comment by himorin** [comment]
read through (roughly), and applied minor fixes as 336e14b. I've finished my review.

**Comment by yonaomi** [comment]
「リンク・フィッシング不可な認証」

要員→要因

ですかね？

**Comment by yonaomi** [comment]
Adlam (Fulah)、N'Ko、Osage
とは、日本語で表すとどうなるでしょうか？

アドラム文字、ンコ文字、オセージ語？

「文字」と「言語」が違いそうな

**Comment by himorin** [comment]
> Adlam (Fulah)、N'Ko、Osage
> とは、日本語で表すとどうなるでしょうか？

アドラム文字（フラニ語）、ンコ文字、オセージ語、ですね。確かに片仮名の方がいいんですかねぇ。。
前者２つは人工文字で、フラニ語は元の言語も方言があるのか複数の言語になるのかも決着してない、ンコ文字は複数言語で利用されてるので、文字と言語の表記のずれは仕方なさそうです。

**Comment by himorin** [comment]
ここまで 869ef21 で反映。

**Comment by himorin** [comment]
published. closing this
