### ISSUE TITLE
日本語での用紙回転の縦書き

### ISSUE THREAD

**Issue by himorin** [himorin/w3c-memo#6]
資料

- [条例・規則作成の手引 / 地方自治法規実務研究会](https://www.amazon.co.jp/dp/4474070895)
- [公文例規定、サンプル](https://www.city.yokosuka.kanagawa.jp/reiki/reiki_honbun/g204RG00000106.html)
- [左横書き実施の訓令、サンプル](http://www.city.kitaibaraki.lg.jp/reiki_int/reiki_honbun/e014RG00000081.html)
- [左横書きの実施について通知](https://www.mhlw.go.jp/web/t_doc?dataId=00ta0024&dataType=1&pageNo=1)
- [公文書管理規定ガイドライン](https://www.pref.mie.lg.jp/common/content/000873158.pdf)
- [新旧対照表ガイドライン、サンプル](https://commons.wikimedia.org/wiki/File:%E6%96%B0%E6%97%A7%E5%AF%BE%E7%85%A7%E8%A1%A8%E6%96%B9%E5%BC%8F%E3%81%AB%E3%82%88%E3%82%8B%E6%9D%A1%E4%BE%8B%E7%AD%89%E3%81%AE%E4%B8%80%E9%83%A8%E6%94%B9%E6%AD%A3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%EF%BC%88%E3%83%8D%E3%83%83%E3%83%88%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E6%8E%B2%E8%BC%89%E8%B3%87%E6%96%99%EF%BC%89%EF%BC%88%E5%B9%B3%E6%88%9030%E5%B9%B412%E6%9C%88%EF%BC%91%E6%97%A5%E4%B8%89%E9%87%8D%E7%9C%8C%E7%B7%8F%E5%8B%99%E9%83%A8%E6%B3%95%E5%8B%99%E3%83%BB%E6%96%87%E6%9B%B8%E8%AA%B2%EF%BC%89.pdf)

ref.
- https://github.com/w3c/type-samples/issues/96
- csswg?

**Comment by gminky** [comment]
参考まで。
[文書の左横書き実施要領（昭和36年宿毛市訓令第１号）](http://www.city.sukumo.kochi.jp/reiki_int/reiki_honbun/o309RG00000057.html)の別紙２、[文書の左横書実施要領（昭和47年阪南市訓令第１号）](http://www.city.hannan.lg.jp/static/reiki_int/reiki_honbun/k234RG00000050.html)の別記２、[文書の左横書き実施要領（昭和36年４月12日豊浦町）](https://www.town.toyoura.hokkaido.jp/contents/reiki/reiki_honbun/o200RG00000052.html)の第８、[津和野町文書の左横書き実施要領（平成17年津和野町訓令第14号）](https://www1.g-reiki.net/tsuwano/reiki_honbun/r129RG00000047.html)の別表第２の最終頁は、図解も載っているようです。

**Comment by himorin** [comment]
no action expected. closing.
